# main text of home
name: Shahzeen Nasim
bio: writer living in New York

# twitter summary info
#description: 

#picture: 

url: http://shahzeenn.github.io
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: @__shahzeen
#github: mygithub
email: shahzeen.nasim@gmail.com
instagram: @__shahzeen

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
